### ISSUE TITLE
Use Operate to query process state

### ISSUE THREAD

**Issue by j-lindner** [camunda-community-hub/message-correlator#15]
Instead of implementing a quasi-synchronous 'query process state' event-based SubProcess, Operate could be queried to get that information.

(Operate's eventual consistency would have to be considered, though).

**Comment by falko** [comment]
When messages overtake each other due to a race condition, they will likely arrive within milliseconds of each other and then the eventual consistency will likely mean that the Operate API delivers and outdated result, thus leading to more synthetic messages. Operate is only an option, when the messages arrive with sufficient distance from each other, but in that case the workload of the engine is likely not that high that the direct queries to the process need to be prevented.

**Comment by falko** [comment]
The better way to prevent asking for process state would be better message correlation feedback on publish message.

**Comment by j-lindner** [comment]
won't implement this as of now; updated reasoning in README (see https://github.com/camunda-community-hub/message-correlator/commit/01137482bc65a55a7f83b201535c86cd531dcc37)
